# Generated by Django 4.1.7 on 2023-11-11 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ams', '0006_asset_asset_rated_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_seq_num', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='WORK SEQ NUM must be a positive number')])),
                ('machine_failure_breakdown', models.CharField(blank=True, max_length=255, null=True)),
                ('description_of_work', models.TextField(blank=True, max_length=600, null=True)),
                ('work_type', models.CharField(blank=True, choices=[('Repair', 'Repair'), ('Preventive Maintenance', 'Preventive Maintenance'), ('Fabrication', 'Fabrication'), ('Equipment Setup', 'Equipment Setup'), ('General Jobs', 'General Jobs')], max_length=50, null=True)),
                ('root_cause', models.TextField(blank=True, max_length=600, null=True)),
                ('job_start', models.DateTimeField(blank=True, null=True)),
                ('job_end', models.DateTimeField(blank=True, null=True)),
                ('time_consumed', models.DurationField(blank=True, null=True)),
                ('affecting_production', models.DurationField(blank=True, null=True)),
                ('affecting_time', models.DurationField(blank=True, null=True)),
                ('equipment_code', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=255, null=True)),
                ('system', models.CharField(blank=True, choices=[('Process', 'Process'), ('Civil', 'Civil'), ('Auxiliary', 'Auxiliary'), ('Plant Water', 'Plant Water'), ('Power', 'Power'), ('Steam', 'Steam'), ('Compressed Air', 'Compressed Air'), ('FFW', 'FFW')], default='Process', max_length=100, null=True)),
                ('affecting_bagging', models.BooleanField(blank=True, default=False)),
                ('machine_failure', models.BooleanField(blank=True, default=False)),
                ('type_of_stop_time', models.CharField(blank=True, choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned')], default=None, max_length=20, null=True)),
                ('work_center', models.CharField(blank=True, choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Instrumentation & Controls', 'Instrumentation & Controls'), ('Fabrication', 'Fabrication'), ('Lubrication', 'Lubrication')], default=None, max_length=100, null=True)),
                ('personnel_assigned', models.CharField(blank=True, max_length=255, null=True)),
                ('parts_replaced', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_of_parts', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Waiting for Parts', 'Waiting for Parts'), ('On-going', 'On-going'), ('Completed', 'Completed'), ('Pending', 'Pending')], default=None, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('spare_details', models.TextField(blank=True, null=True)),
                ('notification_num', models.CharField(blank=True, max_length=255, null=True)),
                ('include_log', models.BooleanField(blank=True, default=True)),
                ('equipment_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams.asset')),
            ],
        ),
    ]
