# Generated by Django 4.1.7 on 2023-09-17 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='include_log',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='system',
            field=models.CharField(choices=[('Process', 'Process'), ('Civil', 'Civil'), ('Auxiliary', 'Auxiliary'), ('Plant Water', 'Plant Water'), ('Power', 'Power'), ('Steam', 'Steam'), ('Compressed Air', 'Compressed Air'), ('FFW', 'FFW')], default='Process', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='description_of_work',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='root_cause',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='wo_seq_num',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='WORK SEQ NUM must be a positive number')]),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='work_center',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Instrumentation & Controls', 'Instrumentation & Controls'), ('Fabrication', 'Fabrication'), ('Lubrication', 'Lubrication')], max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='work_type',
            field=models.CharField(choices=[('Repair', 'Repair'), ('Preventive Maintenance', 'Preventive Maintenance'), ('Fabrication', 'Fabrication'), ('Equipment Setup', 'Equipment Setup'), ('General Jobs', 'General Jobs')], max_length=50),
        ),
    ]
