# Generated by Django 4.1.7 on 2023-12-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_plantassignment'),
        ('drms', '0002_maintenancelog_log_reporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='plant_of_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='ams.plantassignment'),
        ),
    ]
