# Generated by Django 4.1.7 on 2023-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0003_alter_maintenancelog_affecting_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='quantity_of_parts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='spare_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
