# Generated by Django 4.1.7 on 2023-12-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_plantassignment'),
        ('drms', '0003_alter_maintenancelog_plant_of_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='equipment_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs_equipment', to='ams.asset'),
        ),
    ]
