# Generated by Django 4.1.7 on 2023-09-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0004_alter_maintenancelog_quantity_of_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='notification_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
