# Generated by Django 4.1.7 on 2024-01-28 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drms', '0004_alter_maintenancelog_equipment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maintenance_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='drms.maintenancelog')),
            ],
        ),
    ]
