# Generated by Django 4.1.7 on 2023-09-25 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0005_alter_maintenancelog_notification_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='equipment_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='parts_replaced',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='wo_seq_num',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='WORK SEQ NUM must be a positive number')]),
        ),
    ]
