# Generated by Django 4.1.7 on 2024-02-02 08:25

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0008_asset_critical_asset_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drms', '0005_maintenancelogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelogcomment',
            name='comment_text',
            field=models.TextField(max_length=1000),
        ),
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('planned_production_time', models.DurationField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.timedelta(days=1))])),
                ('output', models.IntegerField(blank=True, null=True)),
                ('output_unit', models.CharField(blank=True, choices=[('Bags', 'Bags'), ('Liters', 'Liters'), ('Barrels', 'Barrels')], default=None, max_length=20, null=True)),
                ('log_reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plant_of_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_data', to='ams.plantassignment')),
            ],
        ),
    ]
