# Generated by Django 4.1.7 on 2024-02-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0006_alter_maintenancelogcomment_comment_text_plantdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancelogcomment',
            options={'ordering': ('timestamp',)},
        ),
    ]
