# Generated by Django 4.1.7 on 2023-09-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0006_alter_maintenancelog_equipment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='description_of_work',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='root_cause',
            field=models.TextField(max_length=600),
        ),
    ]
