# Generated by Django 4.1.7 on 2023-10-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0007_alter_maintenancelog_description_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='affecting_bagging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='affecting_production',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='affecting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='description_of_work',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='include_log',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='job_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='job_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='machine_failure',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='machine_failure_breakdown',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='personnel_assigned',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='root_cause',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='status',
            field=models.CharField(blank=True, choices=[('Waiting for Parts', 'Waiting for Parts'), ('On-going', 'On-going'), ('Completed', 'Completed'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='system',
            field=models.CharField(blank=True, choices=[('Process', 'Process'), ('Civil', 'Civil'), ('Auxiliary', 'Auxiliary'), ('Plant Water', 'Plant Water'), ('Power', 'Power'), ('Steam', 'Steam'), ('Compressed Air', 'Compressed Air'), ('FFW', 'FFW')], default='Process', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='time_consumed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='type_of_stop_time',
            field=models.CharField(blank=True, choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='work_center',
            field=models.CharField(blank=True, choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Instrumentation & Controls', 'Instrumentation & Controls'), ('Fabrication', 'Fabrication'), ('Lubrication', 'Lubrication')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='work_type',
            field=models.CharField(blank=True, choices=[('Repair', 'Repair'), ('Preventive Maintenance', 'Preventive Maintenance'), ('Fabrication', 'Fabrication'), ('Equipment Setup', 'Equipment Setup'), ('General Jobs', 'General Jobs')], max_length=50, null=True),
        ),
    ]
