# Generated by Django 4.1.7 on 2023-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0008_alter_maintenancelog_affecting_bagging_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='affecting_bagging',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='include_log',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='machine_failure',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
