# Generated by Django 4.1.7 on 2023-10-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0009_alter_maintenancelog_affecting_bagging_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='type_of_stop_time',
            field=models.CharField(blank=True, choices=[('Planned', 'Planned'), ('Unplanned', 'Unplanned')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='work_center',
            field=models.CharField(blank=True, choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Instrumentation & Controls', 'Instrumentation & Controls'), ('Fabrication', 'Fabrication'), ('Lubrication', 'Lubrication')], default='', max_length=100, null=True),
        ),
    ]
