# Generated by Django 4.1.7 on 2023-10-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0011_alter_maintenancelog_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='affecting_production',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='affecting_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='time_consumed',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
