# Generated by Django 4.1.7 on 2023-10-29 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drms', '0012_alter_maintenancelog_affecting_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancelog',
            name='wo_seq_num',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='WORK SEQ NUM must be a positive number')]),
        ),
    ]
