# Generated by Django 4.1.7 on 2023-04-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_manufacturer', models.CharField(max_length=100)),
                ('asset_model', models.CharField(max_length=100)),
                ('asset_sub_model_01', models.CharField(blank=True, max_length=50)),
                ('asset_sub_model_02', models.CharField(blank=True, max_length=50)),
                ('asset_sub_model_03', models.CharField(blank=True, max_length=50)),
                ('asset_year', models.IntegerField(blank=True)),
                ('asset_month', models.CharField(blank=True, max_length=50)),
                
            ],
        ),
    ]
