# Generated by Django 4.1.7 on 2023-03-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_manufacturer', models.CharField(max_length=100)),
                ('asset_model', models.CharField(max_length=100)),
                ('asset_year', models.IntegerField(max_length=4)),
                ('asset_month', models.CharField(max_length=50)),
                ('asset_sub_model', models.CharField(max_length=50)),
            ],
        ),
    ]
