# Generated by Django 4.1.7 on 2023-04-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_image_primary',
            field=models.ImageField(default='D:\\Legacy Projects\rmics\rmics\\images\\dphd_1.jpg', upload_to='pics'),
        ),
    ]
