# Generated by Django 4.1.7 on 2023-03-18 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('plant_address', models.CharField(max_length=100)),
                ('plant_business', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_sub_model',
            new_name='asset_sub_model_01',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_sub_model_02',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_sub_model_03',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_year',
            field=models.IntegerField(),
        ),
    ]
