# Generated by Django 4.1.7 on 2023-04-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_asset_asset_image_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_image_primary',
            field=models.ImageField(default='D:\\Legacy Projects\rmics\rmics\\media\\dphd_1.jpg', upload_to='pics'),
        ),
    ]
