# Generated by Django 4.1.7 on 2023-03-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_sub_model_01',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_sub_model_02',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_sub_model_03',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
