# Generated by Django 4.1.7 on 2023-09-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_alter_asset_asset_image_primary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_sub_model_01',
            new_name='asset_drive_details',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_sub_model_02',
            new_name='asset_sub_type',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_sub_model_03',
            new_name='asset_type',
        ),
    ]
