# Generated by Django 4.1.7 on 2023-09-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_rename_asset_sub_model_01_asset_asset_drive_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_year',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
