# Generated by Django 4.1.7 on 2023-09-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_alter_asset_asset_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_rated_capacity',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
