# Generated by Django 4.1.7 on 2024-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0007_plantassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='critical_asset_designation',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
