# Generated by Django 4.1.7 on 2023-10-30 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='D:\\Legacy Projects\rmics\rmics\\media\\smcrmi_logo_1.jpg', upload_to='pics')),
                ('position', models.CharField(blank=True, choices=[('Material Custodian', 'Material Custodian'), ('Maintenance Planner', 'Maintenance Planner'), ('Supervisor', 'Supervisor'), ('Engineering Head', 'Engineering Head'), ('Area Engineering Head', 'Area Engineering Head'), ('National Operations Manager', 'National Operations Manager'), ('General Manager', 'General Manager')], max_length=100, null=True)),
                ('profession', models.CharField(blank=True, choices=[('Electrical Engineer', 'Electrical Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Civil Engineer', 'Civil Engineer'), ('Electronics Engineer', 'Electronics Engineer'), ('National Certificate', 'National Certificate')], max_length=100, null=True)),
                ('plant_assignment', models.CharField(blank=True, choices=[('BMEG-Bataan 1', 'BMEG-Bataan 1'), ('BMEG-Bataan 2', 'BMEG-Bataan 2'), ('BMEG-Echague', 'BMEG-Echague'), ('BMEG-Leganes', 'BMEG-Leganes'), ('BMEG-Ormoc', 'BMEG-Ormoc'), ('BMEG-Pavia', 'BMEG-Pavia'), ('BMEG-San Ildefonso', 'BMEG-San Ildefonso'), ('BMEG-Sta. Cruz', 'BMEG-Sta. Cruz'), ('BMEG-Tagoloan', 'BMEG-Tagoloan'), ('BMEG-Tarlac', 'BMEG-Tarlac'), ('BMEG-Pangasinan', 'BMEG-Pangasinan'), ('Mills-Mabini 1', 'Mills-Mabini 1'), ('Mills-Mabini 2', 'Mills-Mabini 2'), ('Mills-Tabangao', 'Mills-Tabangao'), ('BMEG-Mandaue', 'BMEG-Mandaue'), ('Mills-Mabini Premix', 'Mills-Mabini Premix'), ('Monterey-Sumilao', 'Monterey-Sumilao')], max_length=100, null=True)),
                ('area_assignment', models.CharField(blank=True, choices=[('Plant', 'Plant'), ('Area', 'Area'), ('Regional', 'Regional'), ('National', 'National'), ('Functional', 'Functional')], max_length=100, null=True)),
                ('business_unit', models.CharField(blank=True, choices=[('SMFI Feeds', 'SMFI Feeds'), ('SMFI Flour', 'SMFI Flour'), ('SMB Beer', 'SMB Beer')], max_length=100, null=True)),
                ('motto', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
