# Generated by Django 4.1.7 on 2023-11-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuserprofile_plant_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(blank=True, max_length=50, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
