# Generated by Django 4.1.7 on 2023-12-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_plantassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantAssignment',
        ),
    ]
