# Generated by Django 4.1.7 on 2023-12-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuserprofile_plant_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='profile_picture',
            field=models.ImageField(default='smcrmi_logo_1.jpg', upload_to='pics'),
        ),
    ]
