# Generated by Django 4.1.7 on 2024-01-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='certificate',
            field=models.FileField(default='smcrmi_logo_1.jpg', upload_to='certificates/', verbose_name='certificate'),
        ),
    ]
