# Generated by Django 4.1.7 on 2024-01-27 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_alter_reward_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='awardee',
        ),
        migrations.AddField(
            model_name='reward',
            name='awardee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='awardee'),
            preserve_default=False,
        ),
    ]
