# Generated by Django 4.1.7 on 2023-11-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindingsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_of_discovery', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('reported_time', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('findings_title', models.CharField(blank=True, max_length=100, null=True)),
                ('findings_description', models.TextField(blank=True, max_length=700, null=True)),
                ('action_plan', models.TextField(blank=True, max_length=1000, null=True)),
                ('action_plan_schedule', models.DateTimeField(blank=True, null=True)),
                ('parts_availability', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('on-going', 'On-going repair'), ('waiting', 'Waiting for parts'), ('done', 'Done')], max_length=20, null=True)),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
